jenkins:
  build: .
  ports:
    - "8080:8080"
    - "50000:50000"
  volumes:
    - "./jenkins_home:/var/jenkins_home"
  links:
    - "rabbitmq"

rabbitmq:
  image: "rabbitmq:3-management"
  environment:
    RABBITMQ_ERLANG_COOKIE: "SWQOKODSQALRPCLNMEQG"
    RABBITMQ_DEFAULT_USER: "rabbitmq"
    RABBITMQ_DEFAULT_PASS: "rabbitmq"
    RABBITMQ_DEFAULT_VHOST: "/"
  ports:
    - "15672:15672"
    - "5672:5672"
  labels:
    NAME: "rabbitmq1"
